#!/bin/sh

cat LICENSE       || exit 1
cat auto-warn.txt || exit 1
cat <<EOF
package body POSIX.Error is

EOF

echo '  -- Errno values (generated by errno_constants.lua)'
./errno_constants.lua errno_to_int.map || exit 1
echo
echo '  -- Errno mappings (generated by errno_map.lua)'
./errno_map.lua errno_to_int.map errno_to_ada.map || exit 1

cat <<EOF

  function Get_Error return Error_t is
  begin
    return Errno_To_Ada (Errno.Errno_Get);
  end Get_Error;

  procedure Set_Error (Error_Value : in Error_t) is
  begin
    Errno.Errno_Set (Ada_To_Errno (Error_Value));
  end Set_Error;

end POSIX.Error;
EOF
